
# @name Sign in as a user Yanis
# {"token": "<token value>"}
POST http://localhost:3000/auth/sign-in
Content-Type: application/json

{
  "email": "yanis.ghidouche@gmail.com",
  "password": "123456"
}

> {% client.global.set("auth_token", response.body.token) %}

####
# @name Sign up as a user Yanis
POST http://localhost:3000/auth/sign-up
Content-Type: application/json

{
  "email": "yanis.ghidouche@gmail.com",
  "password": "123456"
}
